# Problem Statement

The goal of this project is to predict whether a heart failure patient will be readmitted to the hospital within 30 days.

Hospital readmissions are a major challenge in healthcare because they increase costs and indicate poor patient outcomes.

We use machine learning to analyze both clinical and social factors such as:
- Vital signs (blood pressure, heart rate)
- Clinical markers (BNP, creatinine, sodium)
- Medication and treatment patterns
- Social factors (income level, access to care, medication adherence)

The objective is to build a predictive model that identifies high-risk patients early and helps reduce hospital readmissions.

#### Load dataset and import libbraries

In [79]:
# Import Libraries for handling Data

import pandas as pd
import numpy as np

# Import train-test split
from sklearn.model_selection import train_test_split

# Import Logistic Regression
from sklearn.linear_model import LogisticRegression

# Import evaluation metrics
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Import SMOTE for handling class imbalance
from imblearn.over_sampling import SMOTE

# Import Random Forest model
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.preprocessing import StandardScaler

# Import SVM model
from sklearn.svm import SVC

# Import KNN model
from sklearn.neighbors import KNeighborsClassifier

# Import Naive Bayes model
from sklearn.naive_bayes import GaussianNB

In [7]:
# Load Datasets

df = pd.read_csv('heart_failure_readmission_dataset.csv')

# Data Head

df.head()

,patient_id,age,gender,bmi,bnp,sodium,creatinine,systolic_bp,heart_rate,ace_inhibitor,beta_blocker,diuretic,adherence_score,income_level,distance_to_hospital_km,readmitted_30d
0,12911,76,Male,23.9,738,135.3,1.58,151,93,1,1,0,0.98,Medium,12.4,0
1,12521,77,Male,32.3,405,143.0,1.50,107,74,1,0,1,0.66,Medium,38.8,1
2,10155,42,Male,29.3,399,NaN,1.43,121,97,1,0,1,0.93,Low,43.5,1
3,12088,83,Female,29.1,524,135.1,0.91,114,66,0,1,1,0.54,Low,33.3,1
4,10792,48,Female,24.2,301,139.5,0.54,122,79,1,1,1,0.78,High,21.3,0

In [13]:
# Check dataset shape (rows, columns)

print('Shape of Dataset:',df.shape)

# Check column names 
print("\nColumns:\n", df.columns)

# chedck for Missing values

print("\nMissing values:\n", df.isnull().sum())

# Basic infor about data types
print("\nData info:")
df.info()

Shape of Dataset: (3000, 16)

Columns:
 Index(['patient_id', 'age', 'gender', 'bmi', 'bnp', 'sodium', 'creatinine',
       'systolic_bp', 'heart_rate', 'ace_inhibitor', 'beta_blocker',
       'diuretic', 'adherence_score', 'income_level',
       'distance_to_hospital_km', 'readmitted_30d'],
      dtype='str')

Missing values:
 patient_id                  0
age                         0
gender                      0
bmi                        90
bnp                         0
sodium                     90
creatinine                 90
systolic_bp                 0
heart_rate                  0
ace_inhibitor               0
beta_blocker                0
diuretic                    0
adherence_score             0
income_level                0
distance_to_hospital_km     0
readmitted_30d              0
dtype: int64

Data info:
<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               3000 non-null   int64
 1   age                      3000 non-null   int64
 2   gender                   3000 non-null   str
 3   bmi                      2910 non-null   float64
 4   bnp                      3000 non-null   int64
 5   sodium                   2910 non-null   float64
 6   creatinine               2910 non-null   float64
 7   systolic_bp              3000 non-null   int64
 8   heart_rate               3000 non-null   int64
 9   ace_inhibitor            3000 non-null   int64
 10  beta_blocker             3000 non-null   int64
 11  diuretic                 3000 non-null   int64
 12  adherence_score          3000 non-null   float64
 13  income_level             3000 non-null   str
 14  distance_to_hospital_km  3000 non-null   float64
 15  readmitted_30d           3000 non-null   int64
dtypes: float64(5), int64(9), str(2)
memory usage: 375.1 KB

### Lets Handle missing values (ONLY missing values first)

We saw:

- bmi → 90 missing
- sodium → 90 missing
- creatinine → 90 missing

#### 🧠 Why median?

- Medical data has outliers
- Median is more stable than mean
- Prevents distortion of data

In [15]:
# Fill missing vlues with median (Safe for medical numerical data)

df['bmi'] =df['bmi'].fillna(df['bmi'].median())
df["sodium"] = df["sodium"].fillna(df["sodium"].median())
df["creatinine"] = df["creatinine"].fillna(df["creatinine"].median())

#### 🟢  Encode categorical columns

Now we convert text into numbers so the model can understand it.

In [19]:
# Convert gender into numbers

df['gender'] = df['gender'].map({"Male": 1, "Female": 0})

# Convert income level into numbers

df['income_level'] = df['income_level'].map({
    "Low": 0,
    "Medium": 1,
    "High": 2
})

#### 🟢 Step 4.3: Final Data Check (Before Modeling)

In [ ]:
# Check first 5 rows
df.head()

,patient_id,age,gender,bmi,bnp,sodium,creatinine,systolic_bp,heart_rate,ace_inhibitor,beta_blocker,diuretic,adherence_score,income_level,distance_to_hospital_km,readmitted_30d
0,12911,76,1,23.9,738,135.3,1.58,151,93,1,1,0,0.98,1,12.4,0
1,12521,77,1,32.3,405,143.0,1.50,107,74,1,0,1,0.66,1,38.8,1
2,10155,42,1,29.3,399,138.1,1.43,121,97,1,0,1,0.93,0,43.5,1
3,12088,83,0,29.1,524,135.1,0.91,114,66,0,1,1,0.54,0,33.3,1
4,10792,48,0,24.2,301,139.5,0.54,122,79,1,1,1,0.78,2,21.3,0

In [21]:
# Check data type

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               3000 non-null   int64
 1   age                      3000 non-null   int64
 2   gender                   3000 non-null   int64
 3   bmi                      3000 non-null   float64
 4   bnp                      3000 non-null   int64
 5   sodium                   3000 non-null   float64
 6   creatinine               3000 non-null   float64
 7   systolic_bp              3000 non-null   int64
 8   heart_rate               3000 non-null   int64
 9   ace_inhibitor            3000 non-null   int64
 10  beta_blocker             3000 non-null   int64
 11  diuretic                 3000 non-null   int64
 12  adherence_score          3000 non-null   float64
 13  income_level             3000 non-null   int64
 14  distance_to_hospital_km  3000 non-null   float64
 15  readmitted_30d           3000 non-null   int64
dtypes: float64(5), int64(11)
memory usage: 375.1 KB

In [22]:
# Check if any missing values still exist

df.isnull().sum()

patient_id                 0
age                        0
gender                     0
bmi                        0
bnp                        0
sodium                     0
creatinine                 0
systolic_bp                0
heart_rate                 0
ace_inhibitor              0
beta_blocker               0
diuretic                   0
adherence_score            0
income_level               0
distance_to_hospital_km    0
readmitted_30d             0
dtype: int64

#### 🟢  Train/Test Split
Now we separate:

- features (X)
- target (y)

In [24]:
X= df.drop("readmitted_30d", axis=1)
y = df['readmitted_30d']

In [26]:
# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [27]:
# Check shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (2400, 15)
X_test shape: (600, 15)
y_train shape: (2400,)
y_test shape: (600,)

#### 🟢  Logistic Regression (Baseline Model)

Now we build your first ML model.

In [29]:
# Create model

log_model = LogisticRegression(max_iter=1000)

# Train model

log_model.fit(X_train, y_train)

c:\Users\P15s\OneDrive\Documents\Logistic Regression Project\ml_env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

#### Make predictions

In [30]:
y_pred =log_model.predict(X_test)

#### Evaluate Logistic Regression Model

In [32]:
# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[292  82]
 [128  98]]

In [35]:
# Classification Report
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.78      0.74       374
           1       0.54      0.43      0.48       226

    accuracy                           0.65       600
   macro avg       0.62      0.61      0.61       600
weighted avg       0.64      0.65      0.64       600

In [34]:
# Accuracy
print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred))

Accuracy Score:
0.65

##### 🟢 Model Evaluation Findings (Logistic Regression)

- Overall Accuracy = 65%
- The model is correct 65 out of 100 times
- This is moderate performance
- Not strong enough for healthcare use yet

##### 📊 2. Confusion Matrix Meaning

[[292  82]
 [128  98]]

 - 292 (True Negatives)
→ Correctly predicted patients who will NOT be readmitted
- 82 (False Positives)
→ Model wrongly predicted readmission (alarm but wrong)
- 128 (False Negatives) 🚨
→ Model FAILED to detect real readmitted patients
- 98 (True Positives)
→ Correctly detected readmitted patients

##### Most Important Problem

👉 The model is missing many sick patients

- Recall for class 1 = 0.43

##### This means:
- It only detects 43% of real readmissions
- It misses 57% of high-risk patients

##### Problem Class Imbalance Impact

- Class 0 (no readmission) = majority
- Class 1 (readmission) = minority

###### 👉 So the model learns:

“It is safer to predict 0 most of the time”

## Apply SMOTE (Balance Training Data Only)

In [37]:
# Create SMOTE object

smote = SMOTE(random_state=42)

# Apply SMOTE only on training data

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

#### Check New Class Balance

In [38]:
# Check the new balanced class distribution

print(y_train_smote.value_counts())

readmitted_30d
0    1392
1    1392
Name: count, dtype: int64

- D ataset is now fully balanced
- Both classes have equal importance
- The model will no longer “prefer” class 0
- This should improve recall for class 1 (readmitted patients)

##### Train Logistic Regression (SMOTE data)

In [39]:
# Create model

log_model_smote = LogisticRegression(max_iter=1000)

# Train using SMOTE data

log_model_smote.fit(X_train_smote, y_train_smote)

c:\Users\P15s\OneDrive\Documents\Logistic Regression Project\ml_env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

####  Predict on original test set

In [40]:
# Predict on original test set
y_pred_smote = log_model_smote.predict(X_test)

##### Evaluate SMOTE Logistic Regression Model

In [41]:
# Confusion Matrix

print('Confusion Matrix')
print(confusion_matrix(y_test, y_pred_smote))

Confusion Matrix
[[234 140]
 [ 90 136]]

In [42]:
# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_smote))

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.63      0.67       374
           1       0.49      0.60      0.54       226

    accuracy                           0.62       600
   macro avg       0.61      0.61      0.61       600
weighted avg       0.64      0.62      0.62       600

In [43]:
# Accuracy Score
print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred_smote))

Accuracy Score:
0.6166666666666667

##### 🟢 SMOTE Model Evaluation (Simple Explanation)

###### 📊 Confusion Matrix

[[234 140]
 [ 90 136]]
 
 Class 0 (Not readmitted)
- 234 correctly predicted
- 140 incorrectly predicted

👉 Model is still okay but slightly weaker than before

Class 1 (Readmitted) 🚨 IMPORTANT
- 136 correctly detected (GOOD ✔)
- 90 missed (still errors, but improved)

###### 📈 Key Improvements (VERY IMPORTANT)
Before SMOTE:
- Recall for class 1 = 0.43
- Model was missing most readmitted patients
After SMOTE:
- Recall for class 1 = 0.60 ✔

👉 That is a BIG improvement

###### 🧠 Final Interpretation

- Model now detects more high-risk patients
- Trade-off: slightly more false alarms
- Overall performance is more balanced

###### 📊 Accuracy = 61.6%

Lower than before (expected)
BUT more realistic and useful in healthcare

👉 In medical problems, recall is more important than accuracy

# Train Random Forest Model

We will now build a stronger model and compare it with Logistic Regression.

In [46]:
# Create model

rf_model = RandomForestClassifier(random_state=42)

# Train model on SMOTE data 

rf_model.fit(X_train_smote, y_train_smote)

RandomForestClassifier(random_state=42)

In [47]:
# Make prediction

y_pred_rf = rf_model.predict(X_test)

## Evaluate Random Forest (and compare with Logistic Regression 🚀)

In [48]:
# Confused Matrix
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred_rf))

Confusion Matrix
[[256 118]
 [ 96 130]]

In [49]:
# Classification Report

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.68      0.71       374
           1       0.52      0.58      0.55       226

    accuracy                           0.64       600
   macro avg       0.63      0.63      0.63       600
weighted avg       0.65      0.64      0.65       600

In [50]:
# Accuracy Score

print("\nAccuracy Score:")
print(accuracy_score(y_test,y_pred_rf))

Accuracy Score:
0.6433333333333333

### 🟢 Logistic Regression (SMOTE) vs Random Forest


| Metric              | Logistic Regression | Random Forest |
| ------------------- | ------------------- | ------------- |
| Accuracy            | 61.7%               | 64.3%         |
| Recall (Class 1)    | 0.60                | 0.58          |
| Precision (Class 1) | 0.49                | 0.52          |
| F1-score (Class 1)  | 0.54                | 0.55          |

### Accuracy improved

- Logistic Regression: 61.7%
- Random Forest: 64.3%

Random Forest makes more correct predictions overall.

### ✔ Precision improved

- Logistic Regression: 0.49
- Random Forest: 0.52

This means Random Forest produces fewer false alarms.

### ✔ F1-score improved

- Logistic Regression: 0.54
- Random Forest: 0.55

A small improvement in overall balance between precision and recall.

# Train XGBoost Model

In [57]:
# Create XGBoost model

xgb_model = XGBClassifier(random_state=42,eval_metric="logloss")

# Train model using SMOTE-balanced data
xgb_model.fit(X_train_smote, y_train_smote)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [58]:
# Make predictions

y_pred_xgb =xgb_model.predict(X_test)

## Evaluate XGBoost Model

In [59]:
# Confuion Matrix

print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_xgb))

Confusion Matrix:
[[254 120]
 [111 115]]

In [60]:
# Classification Report
print("\nClassification Report:")
print(classification_report(y_test,y_pred_xgb))

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.68      0.69       374
           1       0.49      0.51      0.50       226

    accuracy                           0.61       600
   macro avg       0.59      0.59      0.59       600
weighted avg       0.62      0.61      0.62       600

In [61]:
# Accuracy Score

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred_xgb))

Accuracy Score:
0.615

## 🚀 XGBoost (SMOTE)

- Accuracy: 61.5%
- Recall (Class 1): 0.51
Key Findings:
- XGBoost did not outperform the other models on this dataset.
- It shows moderate predictive ability.
- It misses more readmitted patients compared to other models.
- Requires further tuning to improve performance.

## 🧠 Overall Conclusion

- SMOTE significantly improved model performance on the minority class.
- There is a clear trade-off between accuracy and recall.
- Logistic Regression performed best for identifying high-risk patients.
- Random Forest performed best in overall balance.
- XGBoost was not the best fit for this dataset without tuning.

# Let Us improve more by Feature Scaling

In [65]:
scaler = StandardScaler()

# Fit only on training data

X_train_scaled = scaler.fit_transform(X_train_smote)

# Transform test data
X_test_scaled = scaler.transform(X_test)

## Support Vector Machine (SVM)

Because it is strong for classification problems.

In [68]:
# Create SVM model
svm_model = SVC()

# Train on scaled SMOTE data
svm_model.fit(X_train_scaled, y_train_smote)

SVC()

In [69]:
# Make predictions
y_pred_svm = svm_model.predict(X_test_scaled)

In [70]:
# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_svm))

Confusion Matrix:
[[253 121]
 [ 85 141]]

In [71]:
# Classification Report
print("\nClassification Report:")
print(classification_report(y_test,y_pred_svm))

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.68      0.71       374
           1       0.54      0.62      0.58       226

    accuracy                           0.66       600
   macro avg       0.64      0.65      0.64       600
weighted avg       0.67      0.66      0.66       600

In [72]:
# Accuracy Score
print('\nAccuracy Score:')
print(accuracy_score(y_test, y_pred_svm))

Accuracy Score:
0.6566666666666666

#### 🟢 SVM Model Evaluation 
[[253 121]
 [ 85 141]]

### 🧠 What this means

✔ Class 0 (Not readmitted)
- 253 correct predictions
- 121 wrong predictions

👉 Model is fairly good at identifying stable patients

### Class 1 (Readmitted patients 🚨)

- 141 correctly detected ✔ (GOOD improvement)
- 85 missed ❌ (still some errors)

👉 This is important improvement in recall

## K-Nearest Neighbors (KNN)
KNN is a distance-based model, so it works well with your scaled data ✔

In [74]:
# Create KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train model
knn_model.fit(X_train_scaled, y_train_smote)

KNeighborsClassifier()

In [75]:
# Make predictions
y_pred_knn = knn_model.predict(X_test_scaled)

In [76]:
# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))

Confusion Matrix:
[[241 133]
 [ 93 133]]

In [77]:
# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_knn))

Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.64      0.68       374
           1       0.50      0.59      0.54       226

    accuracy                           0.62       600
   macro avg       0.61      0.62      0.61       600
weighted avg       0.64      0.62      0.63       600

In [78]:
# Accuracy Score
print("\nAccurcy Score:")
print(accuracy_score(y_test, y_pred_knn))

Accurcy Score:
0.6233333333333333

## 🟢 KNN Model Evaluation

[[241 133]
 [ 93 133]]

 ### 🧠 What this means

✔ Class 0 (Not readmitted)
- 241 correct predictions
- 133 wrong predictions

👉 Model struggles a bit with stable patients


✔ Class 1 (Readmitted 🚨)
- 133 correctly detected ✔
- 93 missed ❌

👉 It catches moderate number of high-risk patients



| Model               | Accuracy | Recall (Class 1) | Comment             |
| ------------------- | -------- | ---------------- | ------------------- |
| Logistic Regression | 61%      | 0.60             | Good recall         |
| Random Forest       | 64%      | 0.58             | Balanced            |
| XGBoost             | 61%      | 0.51             | Weakest             |
| SVM                 | 66%      | 0.62 ⭐           | Best overall        |
| KNN                 | 62%      | 0.59             | Average performance |

# Let us See Naive Bayes Model

In [ ]:
# Create model
nb_model = GaussianNB()

# Train model (use SMOTE + scaled data? No scaling needed but OK to keep consistent)
nb_model.fit(X_train_smote, y_train_smote)

# Make predictions (use original test set, NOT scaled)
y_pred_nb = nb_model.predict(X_test)

In [81]:
# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_nb))

Confusion Matrix:
[[247 127]
 [ 81 145]]

In [82]:

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_nb))

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.66      0.70       374
           1       0.53      0.64      0.58       226

    accuracy                           0.65       600
   macro avg       0.64      0.65      0.64       600
weighted avg       0.67      0.65      0.66       600

In [83]:
# Accuracy Score
print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred_nb))

Accuracy Score:
0.6533333333333333

# Naive Bayes Evaluation

🧠 What this means

- ✔ Class 0 (Not readmitted)
- 247 correct predictions
- 127 wrong predictions

👉 Model is fairly stable for non-readmitted patients

- Class 1 (Readmitted 🚨)
- 145 correctly detected ✔ (GOOD)
- 81 missed ❌ (better than many models)

👉 This is actually a strong recall improvement

| Model               | Accuracy | Recall (Class 1) | Key Insight        |
| ------------------- | -------- | ---------------- | ------------------ |
| Logistic Regression | 61%      | 0.60             | Good recall        |
| Random Forest       | 64%      | 0.58             | Balanced           |
| XGBoost             | 61%      | 0.51             | Weak               |
| SVM                 | 66%      | 0.62             | Best overall model |
| KNN                 | 62%      | 0.59             | Average            |
| **Naive Bayes**     | **65%**  | **0.64 ⭐**       | Best recall so far |